### ISSUE TITLE
Needing more history

### ISSUE THREAD

**Issue by ehem** [dguidipc/cosmo-android-kernel#1]
There is only a single commit present.  This tells us very little.

Is this a completely 100% generic, unmodified MediaTek kernel source? (no customization, impressive)

Has the Cosmo kernel changed _at all_ over time?  Small differences in behavior make one suspect releases V19 and V22 may not have had the **exact** same kernel.  In such case GPL does require release of source for the differing versions.

**Comment by dguidipc** [comment]
Both Kernel and Bootloader are Cosmo-specific. 
If experimenting, I would suggest using the latest v23 release which is now available in the git repository.

**Comment by ehem** [comment]
Usually you would place a tag "cosmo-v23" on commit 1181a7b1335b641bad87e82b54abfe20c20b4bc6.

I'm still wondering what V19, V22, and V1 had.
